[project]
name = "aidwear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pysio-hermes>=0.5.1",
]

[project.optional-dependencies]
prosthesis = [
    "bleak",
    "numpy",
    "python-can",
    "python-statemachine",
    "pydot",
    "scipy",
    "watchdog",
]
ai = [
    "bleak",
    "python-can",
    "python-statemachine",
    "torch",
    "torchvision",
    "torchcodec",
    "fvcore",
    "pyyaml",
    "pandas",
    "numpy",
    "scipy",
]
visualization = [
    "PyQt6",
    "pyqtgraph",
]

[tool.uv.sources]
pysio-hermes = { git = "https://github.com/maximyudayev/hermes.git" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
