[project]
name = "aidwear"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pysio-hermes>=0.5.0",
]

[project.optional-dependencies]
exo = [
    "bleak",
    "numpy",
    "python-can",
    "python-statemachine",
    "scipy",
    "watchdog",
]
ai = [
    "bleak",
    "python-can",
    "python-statemachine",
    "torch",
    "torchvision",
    "torchcodec",
    "fvcore",
    "pyyaml",
    "pandas",
    "numpy",
    "scipy",
]

[tool.uv.sources]
pysio-hermes = { git = "https://github.com/maximyudayev/hermes.git" }
