"""
Filename: hermes/aidwear/cli/data_container.py
Description: HERMES DataContainer object for the management of the data generated by
    user interaction with the terminal of the running prosthesis of manual
    selection of intent, fatigue, and event control.
"""

from typing import Optional

from hermes.base.data_container import DataContainer

 
class CliDataContainer(DataContainer):
    def __init__(
        self,
        buf_len: Optional[int] = 1000,
        **_
    ) -> None:
        super().__init__()

        self.add_channel(
            bundle_name="intent",
            channel_name="mode",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

        self.add_channel(
            bundle_name="fatigue",
            channel_name="level",
            data_type="float32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="fatigue",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="fatigue",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

        self.add_channel(
            bundle_name="event",
            channel_name="mark",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="event",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="event",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

        self.add_channel(
            bundle_name="safety_stop",
            channel_name="is_pause",
            data_type="bool",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="safety_stop",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="safety_stop",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

    def get_fps(self) -> dict[str, float | None]:
        return {"intent": super()._get_fps("intent", "toa_s")}
