"""
Filename: hermes/revalexo/cli/stream.py
Author: Maxim Yudayev <maxim.yudayev@gmail.com>
Date: 2026-02-20
Version: 1.0
Description: HERMES Stream object for the management of the data generated by
    user interaction with the terminal of the running exoskeleton of manual
    selection of intent, fatigue, and event control.
"""

from hermes.base.stream import Stream


class CliStream(Stream):
    def __init__(self, **_) -> None:
        super().__init__()

        self.add_stream(
            device_name="intent",
            stream_name="mode",
            data_type="uint8",
            sample_size=[1],
        )
        self.add_stream(
            device_name="intent",
            stream_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
        )
        self.add_stream(
            device_name="intent",
            stream_name="toa_s",
            data_type="float64",
            sample_size=[1],
        )

        self.add_stream(
            device_name="fatigue",
            stream_name="level",
            data_type="float32",
            sample_size=[1],
        )
        self.add_stream(
            device_name="fatigue",
            stream_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
        )
        self.add_stream(
            device_name="fatigue",
            stream_name="toa_s",
            data_type="float64",
            sample_size=[1],
        )

        self.add_stream(
            device_name="event",
            stream_name="mark",
            data_type="uint8",
            sample_size=[1],
        )
        self.add_stream(
            device_name="event",
            stream_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
        )
        self.add_stream(
            device_name="event",
            stream_name="toa_s",
            data_type="float64",
            sample_size=[1],
        )

        self.add_stream(
            device_name="safety_stop",
            stream_name="is_pause",
            data_type="bool",
            sample_size=[1],
        )
        self.add_stream(
            device_name="safety_stop",
            stream_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
        )
        self.add_stream(
            device_name="safety_stop",
            stream_name="toa_s",
            data_type="float64",
            sample_size=[1],
        )

    def get_fps(self) -> dict[str, float | None]:
        return {"intent": super()._get_fps("intent", "toa_s")}
