"""
Filename: hermes/notes/data_container.py
Author: Maxim Yudayev <maxim.yudayev@gmail.com>
Date: 2026-05-16
Version: 1.0
Description: HERMES DataContainer object for the management of the data generated by
    user interaction with the terminal during an experiment.
"""

from typing import Optional

from hermes.base.data_container import DataContainer


class NotesDataContainer(DataContainer):
    def __init__(self, buf_len: Optional[int] = 1000, **_) -> None:
        super().__init__()

        self.add_channel(
            bundle_name="event",
            channel_name="type",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="event",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="event",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

    def get_fps(self) -> dict[str, float | None]:
        return {"event": super()._get_fps("event", "toa_s")}
