"""
Filename: hermes/aidwear/visualizer/data_container.py
Description: HERMES DataContainer object for the management of synthetic
    prosthesis telemetry, AI intent predictions, and operating modes
    generated by the DummyProducer Node.
"""

from typing import Optional

from hermes.base.data_container import DataContainer


class VisualizerDummyDataContainer(DataContainer):
    """DataContainer pre-allocating shared-memory channels for all simulated visualizer streams."""

    def __init__(
        self,
        buf_len: Optional[int] = 1000,
        sampling_rate_hz: Optional[float] = 25.0,
        num_classes: Optional[int] = 8,
        **_,
    ) -> None:
        super().__init__()

        buf_len = int(buf_len) if buf_len is not None else 1000
        sampling_rate_hz = (
            float(sampling_rate_hz) if sampling_rate_hz is not None else 25.0
        )
        num_classes = int(num_classes) if num_classes is not None else 8

        # 1. 5 Nicla Sense ME IMU locations
        imu_locations = [
            "torso",
            "thigh_right",
            "thigh_left",
            "shank_right",
            "shank_left",
        ]
        for loc in imu_locations:
            bundle_name = f"nicla_{loc}"
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="toa_s",
                data_type="float64",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="euler",
                data_type="float32",
                sample_size=[3],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="acceleration",
                data_type="float32",
                sample_size=[3],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="gyroscope",
                data_type="float32",
                sample_size=[3],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )

        # 2. 2 Prosthesis Motors (knee, ankle)
        motors = ["knee", "ankle"]
        for m in motors:
            bundle_name = f"motor_{m}"
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="toa_s",
                data_type="float64",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="position",
                data_type="float32",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="velocity",
                data_type="float32",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="current",
                data_type="float32",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )

        # 3. 2 Joint Absolute Encoders (knee, ankle)
        encoders = ["knee", "ankle"]
        for e in encoders:
            bundle_name = f"encoder_{e}"
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="toa_s",
                data_type="float64",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )
            self.add_channel(
                bundle_name=bundle_name,
                channel_name="angle",
                data_type="float32",
                sample_size=[1],
                buf_len=buf_len,
                sampling_rate_hz=sampling_rate_hz,
            )

        # 4. Live AI Intent Predictions
        self.add_channel(
            bundle_name="intent",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="predictions",
            data_type="float32",
            sample_size=[num_classes],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="logits",
            data_type="float32",
            sample_size=[num_classes],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="compute_time_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )

        # 5. Factual Prosthesis Mode
        self.add_channel(
            bundle_name="mode",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="mode",
            channel_name="mode",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="mode",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
        self.add_channel(
            bundle_name="mode",
            channel_name="source",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
            sampling_rate_hz=sampling_rate_hz,
        )
