"""
Filename: hermes/aidwear/gui/data_container.py
Author: Maxim Yudayev <maxim.yudayev@gmail.com>
Date: 2026-02-20
Version: 1.0
Description: HERMES DataContainer object for the management of the data generated by
    user interaction with the Android GUI for the selection of intent and fatigue.
"""

from typing import Optional

from hermes.base.data_container import DataContainer


class PhoneGuiDataContainer(DataContainer):
    def __init__(
        self,
        buf_len: Optional[int] = 1000,
        **_,
    ) -> None:
        super().__init__()

        self.add_channel(
            bundle_name="intent",
            channel_name="mode",
            data_type="int8",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="intent",
            channel_name="timestamp",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

        self.add_channel(
            bundle_name="safety_stop",
            channel_name="is_pause",
            data_type="bool",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="safety_stop",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="safety_stop",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="safety_stop",
            channel_name="timestamp",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )

        self.add_channel(
            bundle_name="calibration_cmd",
            channel_name="type",
            data_type="uint8",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="calibration_cmd",
            channel_name="sequence_id",
            data_type="uint32",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="calibration_cmd",
            channel_name="toa_s",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )
        self.add_channel(
            bundle_name="calibration_cmd",
            channel_name="timestamp",
            data_type="float64",
            sample_size=[1],
            buf_len=buf_len,
        )
