prediction_horizons: [0]

checkpoint: "../weights/DCL_AidWear_Lower_Body_5_IMU_Acc_Only.pt"

modalities:
  raw_imu:
    receptive_field: 180
    column_patterns:
      - "acc_Pelvis_X"
      - "acc_Pelvis_Y"
      - "acc_Pelvis_Z"
      - "acc_Right_Upper_Leg_X"
      - "acc_Right_Upper_Leg_Y"
      - "acc_Right_Upper_Leg_Z"
      - "acc_Left_Upper_Leg_X"
      - "acc_Left_Upper_Leg_Y"
      - "acc_Left_Upper_Leg_Z"
      - "acc_Right_Lower_Leg_X"
      - "acc_Right_Lower_Leg_Y"
      - "acc_Right_Lower_Leg_Z"
      - "acc_Left_Lower_Leg_X"
      - "acc_Left_Lower_Leg_Y"
      - "acc_Left_Lower_Leg_Z"
      - "gyro_Pelvis_X"
      - "gyro_Pelvis_Y"
      - "gyro_Pelvis_Z"
      - "gyro_Right_Upper_Leg_X"
      - "gyro_Right_Upper_Leg_Y"
      - "gyro_Right_Upper_Leg_Z"
      - "gyro_Left_Upper_Leg_X"
      - "gyro_Left_Upper_Leg_Y"
      - "gyro_Left_Upper_Leg_Z"
      - "gyro_Right_Lower_Leg_X"
      - "gyro_Right_Lower_Leg_Y"
      - "gyro_Right_Lower_Leg_Z"
      - "gyro_Left_Lower_Leg_X"
      - "gyro_Left_Lower_Leg_Y"
      - "gyro_Left_Lower_Leg_Z"
    eval_transforms: []

models:
  raw_imu:
    name: DeepConvLSTM
    params:
      channels: 15
      window_size: 180
      conv_kernels: 64
      conv_kernel_size: 11
      lstm_units: 1024
      lstm_layers: 1
      dropout: 0.5
